
[window]
opacity = 1

[font]
size = 12.0

[font.normal]
family = "SpaceMono Nerd Font"
# family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
# family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
# family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "SpaceMono Nerd Font"
# family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[general]
import = [
  "~/.config/alacritty/themes/themes/girlypop.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"

]

