
[window]
opacity = 1

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"

[general]
import = [
  "~/.config/alacritty/themes/themes/girlypop.toml"
]
