# Edited version of catppuccin's mocha flavour for maximum girlypop

[colors.primary]
background = '#320044' # base
foreground = '#EFCBFB' # text
# Bright and dim foreground colors
dim_foreground = '#EFCBFB' # text
bright_foreground = '#EFCBFB' # text

# Cursor colors
[colors.cursor]
text = '#320044' # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#320044' # base
cursor = '#E9A6FF' # lavender

# Search colors
[colors.search.matches]
foreground = '#320044' # base
background = '#C29BCF' # subtext0

[colors.search.focused_match]
foreground = '#320044' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#320044' # base
background = '#C29BCF' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#320044' # base
background = '#F8F3A6' # yellow

[colors.hints.end]
foreground = '#320044' # base
background = '#C29BCF' # subtext0

# Selection colors
[colors.selection]
text = '#320044' # base
background = '#F5E0DC' # rosewater

# Normal colors
[colors.normal]
black = '#592C68' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F8F3A6' # yellow
blue = '#C1FCF5' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#D8B3E5' # subtext1

# Bright colors
[colors.bright]
black = '#6D417B' # surface2
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F8F3A6' # yellow
blue = '#C1FCF5' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#C29BCF' # subtext0

# Dim colors
[colors.dim]
black = '#592C88' # surface1 
red = '#F38BA8' # red 
green = '#A6E3A1' # green
yellow = '#F8F3A6' # yellow
blue = '#C1FCF5' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#D8B3E5' # subtext1
