-- telescope keymaps --
local builtin = require('telescope.builtin')
local api = require('nvim-tree.api')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>t', api.tree.open, {})
vim.keymap.set('n', '<leader>c', api.tree.close, {})
